name: Deploy Documentation for Code Fusion Assesment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install mkdocs mkdocs-material

    - name: Deploy to GitHub Pages
      run: |
        mkdocs gh-deploy --force