# Generated by Django 5.2 on 2025-05-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cca2', models.CharField(db_index=True, help_text='ISO 3166-1 alpha-2 two-letter country codes', max_length=3, unique=True)),
                ('cca3', models.CharField(db_index=True, help_text='ISO 3166-1 alpha-3 three-letter country codes', max_length=3, unique=True)),
                ('ccn3', models.CharField(blank=True, help_text='ISO 3166-1 numeric code (UN M49)', max_length=3, null=True)),
                ('cioc', models.CharField(blank=True, help_text='Code of the International Olympic Committee', max_length=10, null=True)),
                ('fifa', models.CharField(blank=True, help_text='FIFA code', max_length=10, null=True)),
                ('name_common', models.CharField(db_index=True, help_text='common country name', max_length=255, unique=True)),
                ('name_official', models.CharField(db_index=True, help_text='Official country name', max_length=255, unique=True)),
                ('native_name', models.JSONField(blank=True, help_text='Native country name', null=True)),
                ('region', models.CharField(blank=True, help_text='UN demographic regions', max_length=100, null=True)),
                ('subregion', models.CharField(blank=True, help_text='UN demographic subregions', max_length=100, null=True)),
                ('latlng', models.JSONField(blank=True, help_text='Latitude and longitude', null=True)),
                ('capital_info', models.JSONField(blank=True, help_text='Capital cities', null=True)),
                ('area', models.FloatField(blank=True, help_text='Geographical size', null=True)),
                ('landlocked', models.BooleanField(default=False, help_text='Landlocked country')),
                ('capital', models.JSONField(blank=True, help_text='Capital latitude and longitude', null=True)),
                ('borders', models.JSONField(blank=True, help_text='Border countries', null=True)),
                ('tld', models.JSONField(blank=True, help_text='Internet top level domains', null=True)),
                ('languages', models.JSONField(blank=True, help_text='List of official languages', null=True)),
                ('currencies', models.JSONField(blank=True, help_text='List of all currencies', null=True)),
                ('demonyms', models.JSONField(blank=True, help_text='Genderized inhabitants of the country', null=True)),
                ('flag', models.CharField(blank=True, help_text='Link to the svg flag on Flagpedia, v3: flag emoji', max_length=255, null=True)),
                ('flags', models.JSONField(blank=True, help_text='Flagpedia links to svg and png flags', null=True)),
                ('coat_of_arms', models.JSONField(blank=True, help_text='MainFacts.com links to svg and png images', null=True)),
                ('maps', models.JSONField(blank=True, help_text='Link to Google maps and Open Street maps', null=True)),
                ('gini', models.JSONField(blank=True, help_text='Worldbank Gini index', null=True)),
                ('car', models.JSONField(blank=True, help_text='Car distinguised (oval) signs, Car driving side', null=True)),
                ('idd', models.JSONField(blank=True, help_text='International dialing codes', null=True)),
                ('alt_spellings', models.JSONField(blank=True, help_text='Alternate spellings of the country name', null=True)),
                ('status', models.CharField(blank=True, help_text='ISO 3166-1 independence status (the country is considered a sovereign state)', max_length=100, null=True)),
                ('un_member', models.BooleanField(default=False, help_text='UN Member status')),
                ('independent', models.BooleanField(default=False, help_text='SO 3166-1 independence status (the country is considered a sovereign state)')),
                ('start_of_week', models.CharField(blank=True, choices=[('monday', 'Monday'), ('sunday', 'Sunday'), ('saturday', 'Saturday')], help_text='Day the week starts on', max_length=20, null=True)),
                ('population', models.BigIntegerField(blank=True, help_text='Country population', null=True)),
                ('timezones', models.JSONField(blank=True, help_text='Timezones', null=True)),
                ('continents', models.JSONField(blank=True, help_text='List of continents the country is on', null=True)),
                ('translations', models.JSONField(blank=True, help_text='List of country name translations', null=True)),
                ('postal_code', models.JSONField(blank=True, help_text='Country postal codes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this country record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this country record was last updated')),
            ],
        ),
    ]
